version: '3.9'

services:
  app:
    build:
      context: .
    container_name: fastapi_app
    command: >
      sh -c "alembic upgrade head && python src/main.py"
    ports:
      - 8000:8000
    depends_on:
      - migrations
      - redis
  
  db:
    container_name: database_app
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: urls_project
    command: -p 5432
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 6379
    expose:
      - 6379

  celery:
    build:
      context: .
    container_name: celery_worker
    working_dir: /app/src
    command: celery -A tasks.tasks.celery_app worker --loglevel=info
    depends_on:
      - app

  beat:
    build:
      context: .
    container_name: celery_beat
    working_dir: /app/src
    command: celery -A tasks.tasks.celery_app beat --loglevel=info
    depends_on:
      - celery

volumes:
  postgres_data:
