FROM python:3.11-slim

RUN mkdir /test

WORKDIR /test

COPY requirements.txt .

RUN pip install --upgrade pip && pip install -r requirements.txt

COPY . .

RUN cp .env.test .env

CMD ["pytest", "--cov=app", "--cov-report=html", "--cov-report=term"]
