"""Attempt to corrupt

Revision ID: bb912f2bc9b1
Revises: 4515f1bcd97d
Create Date: 2025-03-25 00:35:19.898164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb912f2bc9b1'
down_revision: Union[str, None] = '4515f1bcd97d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
